'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Sparkles, Target, Palette, TrendingUp, MessageSquare, BarChart3, CheckCircle, Star, Zap, Globe, Shield, Sun, Moon, Users, Heart, BookOpen } from 'lucide-react'

const features = [
  { icon: Target, title: 'Brand Discovery & Audit', desc: 'AI analyses your organisation and identifies exactly what your brand needs to stand out — tailored to your sector and the East African market.', color: '#F25C05' },
  { icon: Sparkles, title: 'Brand Strategy Builder', desc: 'Get a complete brand strategy — positioning, audience personas, messaging framework, and tone of voice — generated by AI in minutes.', color: '#D9910B' },
  { icon: Palette, title: 'Visual Identity System', desc: 'Upload your logo, choose your colours and fonts, and let AI build your complete visual identity guidelines.', color: '#1A7A6E' },
  { icon: TrendingUp, title: 'Digital Marketing Strategy', desc: 'A 90-day marketing plan tailored for WhatsApp, Instagram, LinkedIn, TikTok, and Facebook — built for the Kenyan market.', color: '#F25C05' },
  { icon: MessageSquare, title: 'AI Content Engine', desc: 'Generate ready-to-use social media posts, captions, and content calendars in your brand\'s voice — for any platform.', color: '#D9910B' },
  { icon: BarChart3, title: 'Analytics Dashboard', desc: 'Track your brand-building progress, AI usage, and content performance — all in one place.', color: '#1A7A6E' },
]

const whoWeServe = [
  { icon: '🏪', label: 'SMEs & Startups', desc: 'Build a brand that wins customers and justifies premium pricing' },
  { icon: '🏥', label: 'Healthcare', desc: 'Build patient trust and professional credibility' },
  { icon: '🎓', label: 'Education', desc: 'Attract students and communicate your institution\'s value' },
  { icon: '🌱', label: 'NGOs & Social Enterprises', desc: 'Win donor trust and communicate your impact clearly' },
  { icon: '💼', label: 'Professional Services', desc: 'Differentiate your firm and attract premium clients' },
  { icon: '🛒', label: 'E-Commerce', desc: 'Build trust and drive repeat purchases online' },
]

const pricing = [
  { id: 'free', name: 'Free', price: 'KES 0', period: 'forever', desc: 'Start your brand journey', features: ['Brand Discovery Audit', '1 Brand Strategy Report', '10 AI Coach queries/month', 'Basic brand guidelines'], cta: 'Start Free', highlight: false },
  { id: 'growth', name: 'Growth', price: 'KES 1,500', period: '/month', desc: 'For growing organisations', features: ['Full Brand Strategy', '90-Day Marketing Plan', '50 AI queries/month', 'PDF exports', 'Remove BrandOS branding'], cta: 'Start Growth', highlight: true },
  { id: 'pro', name: 'Pro', price: 'KES 3,500', period: '/month', desc: 'For serious brands', features: ['Visual Identity Generator', 'Logo upload & storage', 'Social Media Scheduler', 'Unlimited AI Coach', '3 team members'], cta: 'Start Pro', highlight: false },
  { id: 'agency', name: 'Agency', price: 'KES 8,000', period: '/month', desc: 'For agencies & consultants', features: ['Manage 10 client brands', 'White-label reports', 'Unlimited team members', 'Dedicated account manager', 'Custom onboarding'], cta: 'Contact Us', highlight: false },
]

const testimonials = [
  { name: 'Amina Wanjiku', role: 'Founder, Savanna Skincare', text: 'BrandOS gave me a complete brand strategy in 20 minutes. What would have cost KES 80,000 with a consultant, I got for KES 1,500/month.', rating: 5, sector: 'E-Commerce' },
  { name: 'Rev. David Ochieng', role: 'Director, Nairobi Community Foundation', text: 'As an NGO, we struggled to communicate our impact to donors. BrandOS helped us build a brand that speaks directly to what funders care about.', rating: 5, sector: 'NGO' },
  { name: 'Grace Muthoni', role: 'Principal, Westlands Academy', text: 'We went from zero brand strategy to a complete marketing plan in one afternoon. Our enrolment enquiries increased 40% in the first month.', rating: 5, sector: 'Education' },
]

const stats = [
  { value: '7.4M+', label: 'SMEs in Kenya need this' },
  { value: '60%', label: 'Revenue lost to poor branding' },
  { value: '20 min', label: 'To your first brand strategy' },
  { value: 'KES 1,500', label: 'vs KES 45,000 consultant fee' },
]

export default function LandingPage() {
  const [isDark, setIsDark] = useState(true)

  useEffect(() => {
    const saved = localStorage.getItem('brandos-theme')
    const dark = saved !== 'light'
    setIsDark(dark)
    document.documentElement.setAttribute('data-theme', dark ? 'dark' : 'light')
  }, [])

  const toggleTheme = () => {
    const newDark = !isDark
    setIsDark(newDark)
    const theme = newDark ? 'dark' : 'light'
    localStorage.setItem('brandos-theme', theme)
    document.documentElement.setAttribute('data-theme', theme)
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--bg-primary)' }}>
      {/* NAV */}
      <nav className="fixed top-0 left-0 right-0 z-50 backdrop-blur-xl border-b" style={{ backgroundColor: 'rgba(15,29,38,0.92)', borderColor: 'rgba(255,255,255,0.05)' }}>
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#F25C05] flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className="font-display font-bold text-lg text-white">BrandOS</span>
            <span className="text-white/30 text-sm ml-1">by Ingweplex</span>
          </div>
          <div className="hidden md:flex items-center gap-8">
            <a href="#features" className="text-white/60 hover:text-white text-sm transition-colors">Features</a>
            <a href="#who" className="text-white/60 hover:text-white text-sm transition-colors">Who It's For</a>
            <a href="#pricing" className="text-white/60 hover:text-white text-sm transition-colors">Pricing</a>
            <a href="#testimonials" className="text-white/60 hover:text-white text-sm transition-colors">Reviews</a>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={toggleTheme} className="w-9 h-9 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-white/50 hover:text-white transition-colors">
              {isDark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>
            <Link href="/login" className="text-white/70 hover:text-white text-sm font-medium transition-colors">Sign in</Link>
            <Link href="/signup" className="bg-[#F25C05] hover:bg-[#D94E00] text-white font-semibold px-5 py-2 rounded-xl text-sm transition-all">Get Started Free</Link>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="pt-32 pb-20 px-6 relative overflow-hidden">
        <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[400px] bg-[#F25C05]/8 rounded-full blur-3xl pointer-events-none" />
        <div className="max-w-5xl mx-auto text-center relative">
          <div className="inline-flex items-center gap-2 bg-[#F25C05]/10 border border-[#F25C05]/20 rounded-full px-4 py-2 mb-8">
            <Zap className="w-3.5 h-3.5 text-[#F25C05]" />
            <span className="text-[#F25C05] text-sm font-medium">Africa's first AI brand builder — for every type of organisation</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-display font-bold text-white leading-[1.05] mb-6">
            Build a brand that{' '}
            <span style={{ background: 'linear-gradient(135deg, #F25C05, #D9910B)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
              wins in Africa
            </span>
          </h1>
          <p className="text-xl text-white/60 max-w-3xl mx-auto mb-6 leading-relaxed">
            BrandOS guides businesses, NGOs, schools, and organisations through brand strategy, visual identity, and digital marketing — powered by AI, built for Kenya and East Africa.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-3 mb-10 text-sm text-white/40">
            <span className="flex items-center gap-1.5"><CheckCircle className="w-4 h-4 text-[#1A7A6E]" /> Pay via M-Pesa</span>
            <span className="text-white/20">·</span>
            <span className="flex items-center gap-1.5"><CheckCircle className="w-4 h-4 text-[#1A7A6E]" /> No credit card required</span>
            <span className="text-white/20">·</span>
            <span className="flex items-center gap-1.5"><CheckCircle className="w-4 h-4 text-[#1A7A6E]" /> Cancel anytime</span>
            <span className="text-white/20">·</span>
            <span className="flex items-center gap-1.5"><CheckCircle className="w-4 h-4 text-[#1A7A6E]" /> Swahili support</span>
          </div>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <Link href="/signup" className="bg-[#F25C05] hover:bg-[#D94E00] text-white font-semibold px-8 py-4 rounded-xl text-base transition-all flex items-center gap-2 shadow-lg shadow-[#F25C05]/20">
              Start Building Free <ArrowRight className="w-4 h-4" />
            </Link>
            <Link href="/dashboard" className="bg-white/5 hover:bg-white/10 border border-white/10 text-white font-medium px-8 py-4 rounded-xl text-base transition-all">
              View Demo
            </Link>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {stats.map((stat) => (
              <div key={stat.label} className="bg-white/5 border border-white/8 rounded-2xl p-5">
                <div className="text-2xl font-display font-bold text-[#F25C05] mb-1">{stat.value}</div>
                <div className="text-white/50 text-sm">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* WHO WE SERVE */}
      <section id="who" className="py-20 px-6 bg-white/2">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-display font-bold text-white mb-4">Built for every type of organisation</h2>
            <p className="text-white/50 text-lg max-w-2xl mx-auto">BrandOS adapts its language, strategy, and recommendations to your specific sector — not generic advice.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {whoWeServe.map((item) => (
              <div key={item.label} className="bg-white/5 border border-white/8 rounded-2xl p-5 hover:border-[#F25C05]/30 transition-all">
                <div className="text-3xl mb-3">{item.icon}</div>
                <div className="text-white font-semibold mb-1">{item.label}</div>
                <div className="text-white/50 text-sm">{item.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-display font-bold text-white mb-4">Everything your brand needs</h2>
            <p className="text-white/50 text-lg max-w-2xl mx-auto">Six powerful modules that take you from brand confusion to brand clarity — guided by AI every step of the way.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f) => (
              <div key={f.title} className="bg-white/5 border border-white/8 rounded-2xl p-6 hover:border-[#F25C05]/30 hover:bg-white/8 transition-all group">
                <div className="w-12 h-12 rounded-xl flex items-center justify-center mb-5" style={{ backgroundColor: `${f.color}15`, border: `1px solid ${f.color}30` }}>
                  <f.icon className="w-6 h-6" style={{ color: f.color }} />
                </div>
                <h3 className="text-lg font-display font-semibold text-white mb-2">{f.title}</h3>
                <p className="text-white/50 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* AFRICA FIRST */}
      <section className="py-20 px-6 bg-white/2">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <div className="inline-flex items-center gap-2 bg-[#1A7A6E]/10 border border-[#1A7A6E]/20 rounded-full px-4 py-2 mb-6">
                <Globe className="w-3.5 h-3.5 text-[#1A7A6E]" />
                <span className="text-[#1A7A6E] text-sm font-medium">Built for Africa, not adapted for it</span>
              </div>
              <h2 className="text-4xl font-display font-bold text-white mb-6">Why BrandOS is different</h2>
              <p className="text-white/60 mb-8 leading-relaxed">Canva, Looka, and HubSpot were built for Western markets. They don't understand M-Pesa, WhatsApp-first marketing, Swahili-speaking audiences, or the specific challenges of building a brand in Nairobi. BrandOS does.</p>
              <div className="space-y-4">
                {[
                  { icon: '🇰🇪', text: 'Swahili language support — AI coach responds in Swahili' },
                  { icon: '📱', text: 'Pay via M-Pesa — no credit card required' },
                  { icon: '💬', text: 'WhatsApp-first marketing tools built in' },
                  { icon: '🏥', text: 'Sector-specific for NGOs, healthcare, education, and more' },
                  { icon: '💰', text: 'Pricing in KES — no currency conversion anxiety' },
                  { icon: '🤝', text: 'Built by Ingweplex — a Nairobi-based consultancy' },
                ].map((item) => (
                  <div key={item.text} className="flex items-center gap-3">
                    <span className="text-xl">{item.icon}</span>
                    <span className="text-white/70 text-sm">{item.text}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="bg-white/5 border border-white/8 rounded-3xl p-8">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-[#F25C05]/15 flex items-center justify-center">
                  <MessageSquare className="w-5 h-5 text-[#F25C05]" />
                </div>
                <div>
                  <div className="text-white font-semibold text-sm">AI Brand Coach</div>
                  <div className="flex items-center gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-[#1A7A6E] animate-pulse" /><span className="text-white/40 text-xs">Online · Kenyan market expert</span></div>
                </div>
              </div>
              <div className="space-y-4">
                <div className="bg-[#0F1D26]/60 rounded-2xl rounded-tl-sm p-4 text-sm text-white/70 leading-relaxed">Habari! I'm your AI brand coach. Whether you're a business, NGO, school, or startup — I'll help you build a brand that resonates with your audience in Kenya. 🇰🇪</div>
                <div className="bg-[#F25C05]/10 border border-[#F25C05]/20 rounded-2xl rounded-tr-sm p-4 text-sm text-white/80 leading-relaxed ml-8">We're an NGO focused on youth empowerment in Nairobi. How do we attract more donors?</div>
                <div className="bg-[#0F1D26]/60 rounded-2xl rounded-tl-sm p-4 text-sm text-white/70 leading-relaxed">For NGOs, donor trust is built through three things: clear impact evidence, authentic storytelling, and professional brand presentation. Let me build you a brand strategy that speaks directly to what Kenyan and international donors care about...</div>
              </div>
              <div className="mt-4 flex items-center gap-2">
                <div className="flex-1 bg-[#0F1D26]/60 rounded-xl px-4 py-2.5 text-white/30 text-sm">Ask your brand coach anything...</div>
                <button className="w-9 h-9 bg-[#F25C05] rounded-xl flex items-center justify-center"><ArrowRight className="w-4 h-4 text-white" /></button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section id="testimonials" className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-display font-bold text-white mb-4">Organisations across East Africa love BrandOS</h2>
            <p className="text-white/50">Real results from businesses, NGOs, and institutions</p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t) => (
              <div key={t.name} className="bg-white/5 border border-white/8 rounded-2xl p-6">
                <div className="flex items-center gap-2 mb-4">
                  <div className="flex gap-1">{Array.from({ length: t.rating }).map((_, i) => <Star key={i} className="w-4 h-4 text-[#D9910B] fill-[#D9910B]" />)}</div>
                  <span className="bg-[#F25C05]/10 text-[#F25C05] text-[10px] font-bold px-2 py-0.5 rounded-full">{t.sector}</span>
                </div>
                <p className="text-white/70 text-sm leading-relaxed mb-6">"{t.text}"</p>
                <div>
                  <div className="text-white font-semibold text-sm">{t.name}</div>
                  <div className="text-white/40 text-xs mt-0.5">{t.role}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="py-20 px-6 bg-white/2">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-display font-bold text-white mb-4">Simple, honest pricing in KES</h2>
            <p className="text-white/50">Pay via M-Pesa or card. Cancel anytime. No hidden fees.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {pricing.map((plan) => (
              <div key={plan.id} className={`rounded-2xl p-6 border transition-all ${plan.highlight ? 'bg-[#F25C05] border-[#F25C05] shadow-2xl shadow-[#F25C05]/20 scale-[1.02]' : 'bg-white/5 border-white/8 hover:border-white/20'}`}>
                {plan.highlight && <div className="text-white/80 text-xs font-bold uppercase tracking-wider mb-3">Most Popular</div>}
                <div className={`text-sm font-medium mb-1 ${plan.highlight ? 'text-white/80' : 'text-white/50'}`}>{plan.name}</div>
                <div className="text-3xl font-display font-bold mb-1 text-white">{plan.price}</div>
                <div className={`text-sm mb-1 ${plan.highlight ? 'text-white/70' : 'text-white/40'}`}>{plan.period}</div>
                <div className={`text-xs mb-6 ${plan.highlight ? 'text-white/70' : 'text-white/40'}`}>{plan.desc}</div>
                <div className="space-y-3 mb-8">
                  {plan.features.map((f) => (
                    <div key={f} className="flex items-start gap-2">
                      <CheckCircle className={`w-4 h-4 mt-0.5 flex-shrink-0 ${plan.highlight ? 'text-white' : 'text-[#1A7A6E]'}`} />
                      <span className={`text-sm ${plan.highlight ? 'text-white/90' : 'text-white/60'}`}>{f}</span>
                    </div>
                  ))}
                </div>
                <Link href="/signup" className={`block text-center py-3 rounded-xl font-semibold text-sm transition-all ${plan.highlight ? 'bg-white text-[#F25C05] hover:bg-white/90' : 'bg-[#F25C05]/10 text-[#F25C05] border border-[#F25C05]/20 hover:bg-[#F25C05]/20'}`}>
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
          <div className="mt-8 text-center">
            <p className="text-white/30 text-sm">All plans include: M-Pesa payments · Secure data storage · Email support · Cancel anytime</p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6">
        <div className="max-w-3xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-[#F25C05]/10 border border-[#F25C05]/20 rounded-full px-4 py-2 mb-8">
            <Shield className="w-3.5 h-3.5 text-[#F25C05]" />
            <span className="text-[#F25C05] text-sm font-medium">No credit card required · Pay via M-Pesa · Cancel anytime</span>
          </div>
          <h2 className="text-5xl font-display font-bold text-white mb-6">Your brand deserves to be seen</h2>
          <p className="text-white/60 text-lg mb-10">Join organisations across Kenya and East Africa building powerful brands with BrandOS. Start free today.</p>
          <Link href="/signup" className="bg-[#F25C05] hover:bg-[#D94E00] text-white font-semibold px-10 py-4 rounded-xl text-lg transition-all inline-flex items-center gap-2 shadow-lg shadow-[#F25C05]/20">
            Start Building Your Brand <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-white/5 py-12 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="w-7 h-7 rounded-lg bg-[#F25C05] flex items-center justify-center"><Sparkles className="w-3.5 h-3.5 text-white" /></div>
                <span className="font-display font-bold text-white">BrandOS</span>
              </div>
              <p className="text-white/30 text-sm leading-relaxed">AI-powered brand building for African businesses, NGOs, and organisations.</p>
              <p className="text-white/20 text-xs mt-3">by Ingweplex · Nairobi, Kenya</p>
            </div>
            <div>
              <div className="text-white/50 text-xs font-semibold uppercase tracking-wider mb-4">Product</div>
              <div className="space-y-2">
                {['Features', 'Pricing', 'Who It\'s For', 'Admin'].map(l => <a key={l} href="#" className="block text-white/30 text-sm hover:text-white transition-colors">{l}</a>)}
              </div>
            </div>
            <div>
              <div className="text-white/50 text-xs font-semibold uppercase tracking-wider mb-4">Sectors</div>
              <div className="space-y-2">
                {['SMEs & Startups', 'NGOs', 'Education', 'Healthcare', 'Professional Services'].map(l => <a key={l} href="#" className="block text-white/30 text-sm hover:text-white transition-colors">{l}</a>)}
              </div>
            </div>
            <div>
              <div className="text-white/50 text-xs font-semibold uppercase tracking-wider mb-4">Contact</div>
              <div className="space-y-2">
                <a href="mailto:Ingweplex@gmail.com" className="block text-white/30 text-sm hover:text-white transition-colors">Ingweplex@gmail.com</a>
                <a href="https://wa.me/254798936316" className="block text-white/30 text-sm hover:text-white transition-colors">+254 798 936 316</a>
                <a href="https://ingweplex.site" className="block text-white/30 text-sm hover:text-white transition-colors">ingweplex.site</a>
              </div>
            </div>
          </div>
          <div className="border-t border-white/5 pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="text-white/20 text-sm">© 2026 Ingweplex Business & Branding Consultancy. All rights reserved.</div>
            <div className="flex items-center gap-6 text-sm text-white/30">
              <a href="#" className="hover:text-white transition-colors">Privacy Policy</a>
              <a href="#" className="hover:text-white transition-colors">Terms of Service</a>
              <a href="#" className="hover:text-white transition-colors">Cookie Policy</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}